### ISSUE TITLE
Add Michael and Lisa to about page

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/theme#121]
@michaelbeil @wordmaid

Could I get a picture and a bio from each of you? For size of image and text, see: http://affiliatewp.com/about/

@michaelbeil I could use your GitHub one if you're cool with that:
https://avatars1.githubusercontent.com/u/4752949?v=3&s=400

**Comment by michaelbeil** [comment]
Maybe.

**Comment by michaelbeil** [comment]
Yea, that may be too small. Bio coming.

**Comment by sumobi** [comment]
Michael's:

> Michael Beil is an avid WordPress user. He began his WordPress journey as a side job when a friend asked for some help in 2011, and he has not looked back since. As part of the AffiliateWP crew, he helps with support, testing, and sharing GIFs. 

> When Michael needs to get from point A to point B, he hits a button that activates a rocket on his wheelchair.

> Michael is from the land of cheese and lakes, that is Madison, Wisconsin, where he enjoys playing hammered dulcimer, sailing, coffee brewing, and hanging out with his wife.

**Comment by michaelbeil** [comment]
oh forgot bout this. derp.

**Comment by michaelbeil** [comment]
photo: 
https://secure.gravatar.com/avatar/ca66570e8efc90bf4f96200671fc3059.jpg?s=512&d=https%3A%2F%2Fa.slack-edge.com%2F7fa9%2Fimg%2Favatars%2Fava_0016-512.png

**Comment by pippinsplugins** [comment]
Please add Drew as well

**Comment by michaelbeil** [comment]
@DrewAPicture you are included here :smile:

**Comment by DrewAPicture** [comment]
Oh hey <3

**Comment by DrewAPicture** [comment]
Avatar:
http://f.cl.ly/items/2v1g0O2N2G1j0o3s3H2C/drew_madrid_bw.jpg

Drew Jaynes
@DrewAPicture
http://werdswords.com

I'll work on a bio.

**Comment by wordmaid** [comment]
Here's my bio:

After spending 8 years in Media Advertising and Marketing, Lisa dipped her toe into the WordPress industry in 2014. In 2015 she took the leap, leaving Advertising behind to hone her red-penning and writing skills as The WordMaid, and to become part of the AffiliateWP team. Lisa spends her day sweeping up support tickets, developing docs, and crafting content for AffiliateWP.

Also part of the wider Easy Digital Downloads team, Lisa occasionally helps out with support for Alf’s mate Ed, and lends her eagle eye for content editing whenever needed.

When she’s not sitting - or standing - at her computer, Lisa’s loves are: taking her pooch Jaco for long walks through the bush or along sandy shores; tapping along furiously to (mainly rock) music, pretending she’s the next Steve Gadd or Dave Grohl; and spending time with friends and family over a tipple or two.

**Comment by michaelbeil** [comment]
per a slack convo, @wordmaid, Ed should be Edd :smile:.

**Comment by DrewAPicture** [comment]
Bio: 

Drew Jaynes is a WordPress core developer, documentation enthusiast, and plugin developer who hails from Arvada, Colorado. Drew has been developing with WordPress since 2008, initially freelancing at a university and later working as a developer for an elite WordPress agency before joining the team at AffiliateWP.

Drew's contributions to WordPress are vast and have spanned a multitude of teams including core, docs, meta, support, and community to name a few. He led the effort to document all of the hooks in WordPress core during the 3.7-3.9 release cycles, and has been a credited contributor on every core release since 3.3. To top it off, he even served as the release lead for WordPress 4.2.

In his spare time – other than doing WordPress when he's taking a break from WordPress – Drew likes to travel by plane, train, or automobile just about anywhere, but more often than not it's to the nearby Rocky Mountains for a variety of outdoor fun. Drew has even been known to stop and have a beer with Pippin when he's cruising through Kansas.

**Comment by sumobi** [comment]
Everyone has been added!
https://affiliatewp.com/about/

**Comment by pippinsplugins** [comment]
Excellent!

**Comment by michaelbeil** [comment]
Nice!
