### ISSUE TITLE
Bug in the Pricing Calculator modal

### ISSUE THREAD

**Issue by mindctrl** [AffiliateWP/theme#138]
I changed the default values, and clicked Calculate, and was faced with this:

![image](https://cloud.githubusercontent.com/assets/1254870/17857698/c11bdc1e-6850-11e6-90d0-4ac46547c518.png)

Related: the flow of the calculator doesn't feel ideal to me. The results are at the top, and because the modal is so large and doesn't fit in my screen vertically, I have to scroll up and down to see the results after I make adjustments (assuming I don't click Calculate, which causes the above error). I think a good flow would be have a small intro header, the form fields, and the results at the bottom after the Calculate button, so that everything flows from top to bottom.

**Comment by michaelbeil** [comment]
😄  this was noted on trello as well.

**Comment by sumobi** [comment]
@mindctrl This should be fixed on the dev site. There's no "calculate" button and because of that there's confirmation page.

Regarding the flow, I originally had it the way you described but this resulted in the modal window being too long vertically. Since it's a gravity form I can't exactly shift some inputs up beside each other.

By combining the header with the actual result we're able to show the potential customer a total as the very first thing they see when they open the modal, based on some nice defaults. The wording could change but I'm hoping it's clear enough that the user will adjust the values and see the updated total.

**Comment by michaelbeil** [comment]
This is fixed in v2.
